import React, { useState, useEffect, useRef } from 'react';
import './interviewerDashboard.css';

export default function InterviewerDashboard() {
    const [joinCode, setJoinCode] = useState('');
    const [isJoined, setIsJoined] = useState(false);
    const [sessionData, setSessionData] = useState(null);
    const [errorMsg, setErrorMsg] = useState('');
    const pollInterval = useRef(null);

    const handleJoin = async (e) => {
        e.preventDefault();
        setErrorMsg('');
        if (!joinCode || joinCode.length !== 6) {
            setErrorMsg('Please enter a valid 6-digit Join Code.');
            return;
        }

        await fetchSessionData(joinCode);
    };

    const fetchSessionData = async (code) => {
        try {
            const res = await fetch(`http://localhost:8000/api/session/${code}`);
            if (!res.ok) {
                if (res.status === 404) {
                    setErrorMsg('Invalid code or session ended.');
                    stopPolling();
                    setIsJoined(false);
                } else {
                    setErrorMsg('Server error. Could not connect.');
                }
                return;
            }
            const data = await res.json();
            setSessionData(data);

            if (!isJoined) {
                setIsJoined(true);
                startPolling(code);
            }

            if (!data.is_active) {
                stopPolling();
            }

        } catch (err) {
            console.error(err);
            setErrorMsg('Network error.');
        }
    };

    const startPolling = (code) => {
        if (pollInterval.current) clearInterval(pollInterval.current);
        pollInterval.current = setInterval(() => {
            fetchSessionData(code);
        }, 2000); // Poll every 2 seconds
    };

    const stopPolling = () => {
        if (pollInterval.current) clearInterval(pollInterval.current);
    };

    useEffect(() => {
        return () => stopPolling();
    }, []);

    if (!isJoined || !sessionData) {
        return (
            <div className="dashboard-login">
                <div className="dashboard-login-card">
                    <h2>Live Session Supervisor</h2>
                    <p>Enter the 6-digit Join Code generated by the Candidate's interface to spectate the interview securely.</p>
                    <form onSubmit={handleJoin} className="dashboard-form">
                        <input
                            type="text"
                            placeholder="e.g. 592819"
                            maxLength={6}
                            value={joinCode}
                            onChange={(e) => setJoinCode(e.target.value)}
                        />
                        <button type="submit">Connect to Room</button>
                    </form>
                    {errorMsg && <div className="dashboard-error">{errorMsg}</div>}
                </div>
            </div>
        );
    }

    const { candidate, phase, latest_code, transcripts, browser_warnings, proctor_warnings, is_active } = sessionData;

    return (
        <div className="dashboard-layout">
            {/* Sidebar metadata */}
            <aside className="dashboard-sidebar">
                <div className="sidebar-header">
                    <h3>Recruiter Dashboard</h3>
                    <div className={`status-badge ${is_active ? 'active' : 'ended'}`}>
                        {is_active ? '🔴 LIVE' : '⚪ ENDED'}
                    </div>
                </div>

                <div className="sidebar-section">
                    <h4>Candidate Profile</h4>
                    <p><strong>Name:</strong> {candidate.name}</p>
                    <p><strong>Role:</strong> {candidate.role} ({candidate.experience_years}y)</p>
                    <p><strong>Topic:</strong> {candidate.interview_topic}</p>
                </div>

                <div className="sidebar-section">
                    <h4>Integrity Alerts</h4>
                    {browser_warnings.length > 0 && (
                        <div className="alert-box browser-alert">
                            <strong>Browser Strikes ({browser_warnings.length})</strong>
                            <ul>
                                {browser_warnings.slice(-3).map((w, i) => (
                                    <li key={i}>{w.message}</li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {proctor_warnings.length > 0 && (
                        <div className="alert-box proctor-alert">
                            <strong>Proctor Flags ({proctor_warnings.length})</strong>
                            <ul>
                                {proctor_warnings.slice(-3).map((w, i) => (
                                    <li key={i}>{w}</li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {browser_warnings.length === 0 && proctor_warnings.length === 0 && (
                        <div className="alert-box safe-alert">
                            <strong>Integrity Validated</strong>
                            <p>No cheating or flags detected.</p>
                        </div>
                    )}
                </div>
            </aside>

            {/* Main content grid */}
            <main className="dashboard-main">
                <div className="dashboard-editor-panel">
                    <div className="panel-header">
                        <h4>Live Code Editor</h4>
                    </div>
                    <pre className="live-code-view">
                        <code>{latest_code || "// No code written yet..."}</code>
                    </pre>
                </div>

                <div className="dashboard-transcript-panel">
                    <div className="panel-header">
                        <h4>Conversation Transcript</h4>
                    </div>
                    <div className="transcript-list">
                        {transcripts.length === 0 ? (
                            <p className="empty-text">Conversation hasn't started.</p>
                        ) : (
                            transcripts.map((msg, i) => (
                                <div key={i} className="transcript-item">
                                    <strong>Candidate:</strong> {msg}
                                </div>
                            ))
                        )}
                    </div>
                </div>
            </main>
        </div>
    );
}
